In [22]:
import os
import pandas as pd
import numpy as np

In [23]:
#C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: 
### DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
### has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [54]:
os.getcwd()
filepath='C:\\CPP_Performance\\TSV Files\\UAEdits\\6D105A9CB9AB46169A5AB5B7A4FA1C1B7A35CF4E48E90C41 - 2021-06-16 09-57-11-470.tsv'
output_excel='C:\\CPP_Performance\\TSV Files\\UAEdits\\6D105A9CB9AB46169A5AB5B7A4FA1C1B7A35CF4E48E90C41 - 2021-06-16 09-57-11-470.xlsx'

filepath='C:\\CPP_Performance\\TSV Files\\Parkland School Policy\\15DB645E06504909AE4AA869AC8A2C9D7A35CF4E48E90C41 - 2021-10-20 13-55-28-084.tsv'
output_excel='C:\\CPP_Performance\\TSV Files\\Parkland School Policy\\15DB645E06504909AE4AA869AC8A2C9D7A35CF4E48E90C41 - 2021-10-20 13-55-28-084.xlsx'

df = pd.read_csv(filepath, sep='~', engine='c', header=1
                ,usecols=['begin_end', 'debugID', 'startTime', 'tagName', 'idref']
                ,names=['begin_end', 'debugID', 'startTime', 'tagName', 'idref']
                ,dtype= {'begin_end': 'category', 'debugID': str, 'startTime': str, 'tagName':'category', 'idref':str}
                )
                         #, np.float64, ‘b’: np.int32, ‘c’: ‘Int64’}

In [55]:
df.describe

<bound method NDFrame.describe of          begin_end   debugID     startTime     tagName idref
0                b         1  13:55:28:084        page   NaN
1                b         2  13:55:28:084   worksheet   NaN
2                b         3  13:55:28:084   maxOccurs   NaN
3                e         3  13:55:28:084           1   NaN
4                b         4  13:55:28:084   minOccurs   NaN
...            ...       ...           ...         ...   ...
60810729         e  30405353  14:02:56:997      (true)   NaN
60810730         e  30405228  14:02:56:997     (false)   NaN
60810731         e  30405227  14:02:56:997           0   NaN
60810732         e  30388071  14:02:56:997     actions   NaN
60810733         e         1  14:02:56:997  NewPricing   NaN

[60810734 rows x 5 columns]>

In [38]:
#df.columns = ['begin_end', 'debugID', 'startTime', 'tagName', 'idref']
#df.head(10)

   begin_end           debugID     startTime      tagName idref
0  e(nd)       unique debugID     stop time         value   NaN
1          b                 1  09:57:11:470         page   NaN
2          b                 2  09:57:11:470        group   NaN
3          b                 3  09:57:11:470    minOccurs   NaN
4          e                 3  09:57:11:470            1   NaN
5          b                 4  09:57:11:470    maxOccurs   NaN
6          e                 4  09:57:11:470            1   NaN
7          b                 5  09:57:11:470    minOccurs   NaN
8          e                 5  09:57:11:470            1   NaN
9          b                 6  09:57:11:470  pushContext   NaN

In [56]:
# sanitize data
df.drop(df[df['debugID'] == ' unique debugID '].index, inplace = True)
# convert str to int
df['debugID'] = pd.to_numeric(df['debugID'])

df.head()

  begin_end  debugID     startTime    tagName idref
0         b        1  13:55:28:084       page   NaN
1         b        2  13:55:28:084  worksheet   NaN
2         b        3  13:55:28:084  maxOccurs   NaN
3         e        3  13:55:28:084          1   NaN
4         b        4  13:55:28:084  minOccurs   NaN

In [57]:
df1=df.groupby(['idref'])['idref', 'debugID'].count().sort_values(by='debugID', ascending=False)['idref']
df1.head(20)

<ipython-input-57-811f4d698f35>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df1=df.groupby(['idref'])['idref', 'debugID'].count().sort_values(by='debugID', ascending=False)['idref']

idref
LocationManuscript.StateKey               1010184
True                                       823545
False                                      640475
BuildingPrivate.RiskIterateBPP             544200
RiskInput.BuildingID                       292420
RiskInput.OccupancyID                      290130
CoverageOutput.Type                        287304
RiskInput.LocationID                       284917
PolicyInput.UNIG_EffectiveDate             275355
AccountPrivate.LocationIterateBPP          271806
LocationOutput.StatCodeTerritory           216718
CoveragePrivate.IsSubCoverageCalc          209286
PropertyPolicyInput.PolicyCoverage         202196
RiskInput.Type                             187538
LocationInput.State                        154308
LocationInput.ZipCode                      149368
LocationPrivate.UNIG_ZipCode5Positions     149033
LocationInput.UNIG_ZipCodeInvalid          149032
LocationInput.ZIPCodeValidation            149032
LocationOutput.StatCodeState               145543
Name: idref, dtype: int64

In [59]:
# export to Excel ####
with pd.ExcelWriter(output_excel) as writer:  
    df1.to_excel(writer, sheet_name='frequency')

In [60]:
del df1

In [61]:
#df[df.idref.isin(['LocationPrivate.CheckBuildingLimit', 'BuildingDetailPage.SetLastSelectedOccupancyID', 'OccupancyOutputNonShredded.ApplicableToProperty'])].groupby('idref').count()

In [62]:
df1 = df[df.tagName.isin(['iterator'])].groupby(['idref'])['idref','debugID'].count().sort_values(by='debugID', ascending=False)['idref']
df1.columns=['iterator', 'count']
# export to Excel ####
with pd.ExcelWriter(output_excel, engine="openpyxl", mode='a') as writer:  
    df1.to_excel(writer, sheet_name='iterator')

# Find the immediate parent of the iterator
# count of the iterator index within specific iterator
# elapsed time

<ipython-input-62-f01808b9c5ab>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df1 = df[df.tagName.isin(['iterator'])].groupby(['idref'])['idref','debugID'].count().sort_values(by='debugID', ascending=False)['idref']

In [63]:
# count levels
#df.groupby(['level']).count().sort_values(by='level', ascending=False)

In [64]:
debugList = df[df.tagName.isin(['public', 'private'])].debugID.tolist()
fDebugVal = list(map(int, debugList))

In [65]:
print('public/private count:', len(fDebugVal))
type(fDebugVal)
print(fDebugVal[1:20])
#df[df.debugID=='11']
dfb = df[df.debugID.isin(fDebugVal)].sort_values(by='debugID')

public/private count: 6166406
[12, 16, 21, 30, 37, 42, 52, 55, 57, 61, 65, 70, 76, 81, 83, 90, 95, 97, 116]

In [66]:
dfbstart = dfb[dfb.begin_end=='b'][['debugID', 'startTime', 'idref']]
dfbend = dfb[dfb.begin_end=='e'][['debugID', 'startTime']]
dfbend.columns=['debugID', 'endTime']

In [67]:
dfbstart

,debugID,startTime,idref
10,7,13:55:28:084,True
20,12,13:55:28:084,data.ExecuteTotalResult
26,16,13:55:28:084,PolicyAdminOutputNonShredded.PolicyManuScriptID
36,21,13:55:28:084,LinePrivate.ResetCommissionContributionOnRewrite
45,30,13:55:28:084,PolicyInput.EffectiveDate
...,...,...,...
60810679,30405346,14:02:56:997,PolicyPrivate.UNIG_ChangeAnnivDateTransactionN...
60810685,30405352,14:02:56:997,PolicyPrivate.IsCurrentTransactionEndorse
60810708,30405361,14:02:56:997,LinePrivate.UNIG_ThereAreOptionalProposals
60810712,30405363,14:02:56:997,True
60810718,30405366,14:02:56:997,PolicyPrivate.CheckCurrentPage

In [68]:
dfbend

           debugID       endTime
13               7  13:55:28:084
60543383        12  14:02:42:987
27              16  13:55:28:084
1123            21  13:55:28:084
148             30  13:55:28:084
...            ...           ...
60810692  30405346  14:02:56:997
60810686  30405352  14:02:56:997
60810709  30405361  14:02:56:997
60810713  30405363  14:02:56:997
60810719  30405366  14:02:56:997

[6166406 rows x 2 columns]

In [69]:
dfcombined=pd.merge(dfbend, dfbstart, on=["debugID"])
dfcombined[dfcombined.idref=='LocationPrivate.CheckBuildingLimit']
#dfb.sort_values(by='debugID')
#dfb[dfb.debugID==79806].startTime.tolist()

#dfb[dfb.debugID==11]

,debugID,endTime,startTime,idref
1404882,7127709,13:57:30:900,13:57:30:151,LocationPrivate.CheckBuildingLimit
1415944,7180366,13:57:42:970,13:57:42:063,LocationPrivate.CheckBuildingLimit
3499584,17451722,14:00:02:161,14:00:01:399,LocationPrivate.CheckBuildingLimit
3510646,17504379,14:00:08:343,14:00:07:653,LocationPrivate.CheckBuildingLimit
5520753,27435573,14:02:08:441,14:02:07:782,LocationPrivate.CheckBuildingLimit
5531815,27488230,14:02:14:627,14:02:13:970,LocationPrivate.CheckBuildingLimit
6140223,30279066,14:02:43:955,14:02:43:252,LocationPrivate.CheckBuildingLimit
6151284,30331518,14:02:48:794,14:02:48:028,LocationPrivate.CheckBuildingLimit

In [70]:
dfcombined['timediff'] = pd.DataFrame(( pd.to_datetime(dfcombined['endTime'], format='%H:%M:%S:%f') - pd.to_datetime(dfcombined['startTime'], format='%H:%M:%S:%f')).dt.total_seconds())

In [71]:
from datetime import datetime, timedelta
df1 = dfcombined[dfcombined.timediff > 1.0].sort_values(by='timediff', ascending=False)
del dfcombined

In [72]:
# export to Excel ####
with pd.ExcelWriter(output_excel, engine="openpyxl", mode='a') as writer:  
    df1.to_excel(writer, sheet_name='timing')